import { ITableDataItem } from '../types'

export const TableData: ITableDataItem[] = [
  {
    id: 1,
    name: 'Jacob Geidt',
    email: 'jacob.geidt@gmail.com',
    assessmentCheck: 'completed',
    status: '7 days ago',
    progressStart: 8,
    progressEnd: 80,
    progressNumber: 80,
  },
  {
    id: 2,
    name: 'Adison Passaquindici Arcand',
    email: 'arcandadison@gmail.com',
    assessmentCheck: 'completed',
    status: '10 days ago',
    progressStart: 5,
    progressEnd: 64,
    progressNumber: 64,
  },
  {
    id: 3,
    name: 'Ruben Franci',
    email: 'franci.ruben@gmail.com',
    assessmentCheck: 'completed',
    status: '2 days ago',
    progressStart: 10,
    progressEnd: 100,
    progressNumber: 100,
  },
  {
    id: 4,
    name: 'Ruben Westervelt',
    email: 'westervelt222@gmail.com',
    assessmentCheck: 'completed',
    status: '4 days ago',
    progressStart: 7,
    progressEnd: 76,
    progressNumber: 76,
  },
  {
    id: 5,
    name: 'Alena Mango',
    email: 'alena222mango@gmail.com',
    assessmentCheck: 'completed',
    status: '7 days ago',
    progressStart: 4,
    progressEnd: 43,
    progressNumber: 43,
  },
  {
    id: 6,
    name: 'Brandon Ekstrom Bothman',
    email: 'bothman@gmail.com',
    assessmentCheck: 'completed',
    status: '17 days ago',
    progressStart: 9,
    progressEnd: 89,
    progressNumber: 89,
  },
  {
    id: 7,
    name: 'Justice Chimobi',
    email: 'justice@gmail.com',
    assessmentCheck: 'completed',
    status: '19 days ago',
    progressStart: 9,
    progressEnd: 89,
    progressNumber: 89,
  },
  {
    id: 8,
    name: 'Gift Mccool',
    email: 'mccool.gift32@gmail.com',
    assessmentCheck: 'completed',
    status: '2 days ago',
    progressStart: 44,
    progressEnd: 99,
    progressNumber: 99,
  },
  {
    id: 9,
    name: 'Brent Li',
    email: 'li.brent@gmail.com',
    assessmentCheck: 'completed',
    status: '25 days ago',
    progressStart: 9,
    progressEnd: 39,
    progressNumber: 39,
  },
  {
    id: 10,
    name: 'Kent Otwell',
    email: 'kentotwell@gmail.com',
    assessmentCheck: 'completed',
    status: '3 days ago',
    progressStart: 3,
    progressEnd: 75,
    progressNumber: 75,
  },
  {
    id: 11,
    name: 'Emma Lords',
    email: 'emma@gmail.com',
    assessmentCheck: 'completed',
    status: '14 days ago',
    progressStart: 6,
    progressEnd: 55,
    progressNumber: 55,
  },
  {
    id: 12,
    name: 'Jess Chionh',
    email: 'chionhjess33@gmail.com',
    assessmentCheck: 'completed',
    status: '36 days ago',
    progressStart: 20,
    progressEnd: 40,
    progressNumber: 40,
  },
];